spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=helpdesk
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=1234qwert

jwt.secret=helpdesk-secret-key-2026-development-secret-1234567890-abcdefghijklmnopqrstuvwxyz
jwt.expiration=3600000